init.fs:
  /:
    bin/:
      init:
        + cargo-build: user/init
        + copy: target/_out/init
      tty:
        + cargo-build: user/tty
        + copy: target/_out/tty
      hello:
        + cargo-build: user/hello
        + copy: target/_out/hello
    etc/:
      modules/:
        libhello.so:
          + cargo-build: modules/hello
          + copy: target/_out/libhello.so
        libvfs.so:
          + cargo-build: modules/vfs
          + copy: target/_out/libvfs.so
        libdev.so:
          + cargo-build: modules/dev
          + copy: target/_out/libdev.so
        libpl011.so:
          + cargo-build: modules/pl011
          + copy: target/_out/libpl011.so
        libgictimer.so:
          + cargo-build: modules/gic-timer
          + copy: target/_out/libgictimer.so
      hello.txt:
        + copy-str: "Hello world from file!"
