cargo-features = ["workspace-inheritance"]

[package]
name = "init"
version = { workspace = true }
authors = ["Wenyu Zhao <wenyu.zhao@anu.edu.au>"]
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syscall = { path = "../../libs/syscall" }
vfs = { path = "../../libs/vfs" }
heap = { path = "../../libs/heap" }
log = { path = "../../libs/log" }

[features]
default = []