on:
  pull_request: {}
  push:
    branches:
      - "main"
name: Compile Checks
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: codota/toolchain@v1
  build-debug:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build Test (Debug)
        run: cargo x build
  build-release:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build Test (Release)
        run: cargo x build --release
