on: [push, pull_request]
name: Style Checks
jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: codota/toolchain@v1
      - name: Format Check
        run: cargo fmt --all --check
