on: [push, pull_request]
name: Unit Tests
jobs:
  test-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: codota/toolchain@v1
      - name: Run Unit Tests
        run: cargo x test
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: codota/toolchain@v1
      - name: Run Unit Tests
        run: cargo x test --release
